fail_fast: true
repos:
  - repo: local
    hooks:

      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [ python ]
        args: [ ]
        require_serial: true

      - id: format
        name: format
        entry: bash -c 'black $@ && git add -u' --
        language: python
        types: [ python ]
        require_serial: true

      - id: test
        name: test
        entry: make test
        language: system
        types: [ python ]
        args: [ ]
        require_serial: true
